services:
  - type: web
    name: Backend
    rootDir: Backend
    runtime: java
    buildCommand: ./mvnw clean install -DskipTests
    startCommand: java -jar target/Doodle-Rush-0.0.1-SNAPSHOT.jar
    envVars:
      - key: JAVA_VERSION
        value: 21
    plan: free

  - type: static
    name: Frontend
    rootDir: Frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    plan: free
