services:
  - type: web
    name: backend
    rootDir: backend
    buildCommand: ./mvnw clean install -DskipTests
    startCommand: java -jar target/*.jar
    plan: free

  - type: static_site
    name: front end
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    plan: free
