services:
  - type: web
    name: backend
    rootDir: Backend
    buildCommand: ./mvnw clean install -DskipTests
    startCommand: java -jar target/*.jar
    plan: free

  - type: web
    name: frontend
    env: static
    rootDir: Frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    plan: free
