spring.application.name=Doodle_Rush
#spring.datasource.url=jdbc:derby:./data/doodlerushdb;create=true
#spring.datasource.driver-class-name=org.apache.derby.jdbc.EmbeddedDriver
#spring.datasource.username=
#spring.datasource.password=
#
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
